logging:
  level:
    root: info
    com.example.oauth2: debug
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${PASSWORD}
server:
  port: 8088
  ssl:
    enabled: true
    key-store: ENC(6eQkz7c/XhQ8fVIP9vKH+svycMHFJCUOVBdGUsNPaC2ii9mxQSZ0RXkv+MOXIpvBoRsd6DSAkAyJqFuXPTcPCg==)
    key-store-type: PKCS12
    key-store-password: ENC(X2LIy6i5fuoWHj48YW06Mg==)
spring:
  application:
    name: oauth2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  datasource:
    hikari:
      jdbc-url: ENC(Qc5lHuJk0/Sbpu6t/381z4cr21f1XF7Gckg4pXDw2+Ic2zM17UayeQ==)
      driver-class-name: org.h2.Driver
      maximum-pool-size: 5
      minimum-idle: 1
      pool-name: hikari
      username: ENC(hhaSYbrNr7BcOqRpEW05/Q==)
      password: ENC(PT+u/lz/mluAGjSy9Q0eXg==)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(SJxRiug5z5wL6aWEEABRZyihoYdVIGfHrMjoJhH8WG0H4Eep36sl0Ol7vRjpqXL0q9W4d5NUe/+tNPZMguqmilpUjXIsNKrYdYZh1AoWNBEqpUveUz+QAA==)
            client-secret: ENC(8lwNJlSofTZWw1is5XDPJoJ/Cdh/SH6LgU6ENnoHwNf33+d5Cmox6+ji6HqEFKvI)
            scope:
            - email
          naver:
            client-id: ENC(t5xVGwgB8oCs+XyQgmBJqtb1x0oAkk+Un/sujgN4PfY=)
            client-secret: ENC(vPpZSJHcShViDyJer8Mqi/DSPkhSL2ap)
            redirect-uri: https://latecomer.ddns.net/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
            - email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response