name: CI / CD (NaverCloud)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup-java(temurin)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Execute Gradle build
        run: ./gradlew bootJar -PPASSWORD=${{ secrets.PASSWORD }}
        
      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          connect_timeout: 10s
          script: |
            pkill -f *.jar
            sleep 10
            rm -rf /tmp/oauth2.jar
            
      - name: Transfer file to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          source: "./build/libs/*.jar"
          target: "/tmp/"
          
      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          connect_timeout: 10s
          script: |
            cd /tmp/build/libs
            nohup java -jar -DPASSWORD=${{ secrets.PASSWORD }} oauth2*.jar &
            sleep 10
            cat nohup.out
